version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  post-service:
    build: ./post-service
    container_name: post-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
